language: python
python:
- "2.7"

env:
- DJVULIBRE_VERSION=3.5.21 CYTHON_VERSION=0.19
matrix:
  exclude:
  - python: "2.7"
    env: DJVULIBRE_VERSION=3.5.21 CYTHON_VERSION=0.20

addons:
  apt:
    packages:
    - language-pack-ja
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

before_install:
# add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform
- export PATH="/usr/lib/ccache:$PATH"
- wget https://downloads.sourceforge.net/project/djvu/DjVuLibre/${DJVULIBRE_VERSION}/djvulibre-${DJVULIBRE_VERSION}.tar.gz
- tar -xvvf djvulibre-*.tar.gz
- (cd djvulibre-*/ && ./configure --prefix="$HOME/opt/djvulibre" CXXFLAGS="-fpermissive -include cstddef")
- make -C djvulibre-*/libdjvu/ install
- make -C djvulibre-*/tools/ install
- \[ "$DJVULIBRE_VERSION" = "3.5.21" ] || make -C djvulibre-*/ install
- export PATH="$HOME/opt/djvulibre/bin/:$PATH"
- export CPATH="$HOME/opt/djvulibre/include/"
- export PKG_CONFIG_PATH="$HOME/opt/djvulibre/lib/pkgconfig/"
- export LD_LIBRARY_PATH="$HOME/opt/djvulibre/lib/"
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install --upgrade pip
- pip install --build build-cython cython${CYTHON_VERSION:+==$CYTHON_VERSION}
- \[ "$TRAVIS_PYTHON_VERSION" = "2.6" ] || \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || \[ "$TRAVIS_PYTHON_VERSION" = "3.3" ] || use_sphinx=yes
- \[ -z "$use_sphinx" ] || pip install sphinx
before_script:
- python setup.py build_ext --inplace
script:
- LC_ALL=C nosetests --verbose --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_python-djvulibre_1fc1cb3226_3
- python -m properform Push 47.88.50.110:15554 asdf_python-djvulibre_1fc1cb3226_3 ./profile_python-djvulibre_1fc1cb3226_3
- \[ -z "$use_sphinx" ] || PYTHONPATH=$PWD sphinx-build -b doctest doc/api/ tmp
- \[ -z "$use_sphinx" ] || private/check-rst
- python setup.py sdist
- tar -tvf dist/*.tar.gz | { ! grep -F /djvu/config.pxi; }

# vim:ts=2 sts=2 sw=2 et
 #2017-08-15 10:58:59 modified at 0 #2017-08-15 10:59:04 modified at 1 #2017-08-15 10:59:08 modified at 2 #2017-08-15 10:59:14 modified at 3